[package]
name = "day-01"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "2023_01_1"
path = "src/bin/part-1.rs"

[[bin]]
name = "2023_01_2"
path = "src/bin/part-2.rs"

[build]
target-dir = "target"

[dependencies]
