[package]
name = "day-10"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "2023_10_1"
path = "src/bin/part-1.rs"

[[bin]]
name = "2023_10_2"
path = "src/bin/part-2.rs"

[dependencies]
nom = "7.1.3"
nom-supreme = "0.8.0"
