[package]
name = "day-08"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "2023_08_1"
path = "src/bin/part-1.rs"

[[bin]]
name = "2023_08_2"
path = "src/bin/part-2.rs"

[dependencies]
nom = "7.1.3"
nom-supreme = "0.8.0"
num-integer = "0.1.45"