[package]
name = "day-23"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "2023_23_1"
path = "src/bin/part-1.rs"

[[bin]]
name = "2023_23_2"
path = "src/bin/part-2.rs"

[dependencies]
nom = "7.1.3"
nom-supreme = "0.8.0"
nom_locate = "4.2.0"
itertools = "0.12.0"
glam = "0.25.0"
petgraph = "0.6.4"